# Generated by Django 4.0.4 on 2022-06-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_description_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-avatar.jpg', null=True, upload_to=''),
        ),
    ]
