# Generated by Django 4.0.4 on 2022-05-23 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='base.game'),
        ),
        migrations.AddField(
            model_name='customer',
            name='myGames',
            field=models.ManyToManyField(blank=True, related_name='myGames', to='base.game'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishList',
            field=models.ManyToManyField(blank=True, related_name='wishList', to='base.game'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
