# Generated by Django 4.0.4 on 2022-06-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-avatar.jpg', null=True, upload_to=''),
        ),
    ]
