# Generated by Django 4.0.4 on 2022-05-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_cart_customer_mygames_customer_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
