# Generated by Django 4.0.4 on 2022-06-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_remove_review_customer_review_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='game_list',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
