# Generated by Django 4.0.4 on 2022-06-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_developer_game_list_game_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='developer',
            new_name='devUser',
        ),
    ]
